### PR TITLE
repack as ansible-galaxy installable role

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by gaqzi** [comment]
How would this be used if it was installable as a role?
Have it been changed so Ansible will be able to use this plugin if it's installed through Galaxy now? 

I tried searching for an answer to that but I couldn't find anything on it. :)

**Comment by MartinNowak** [comment]
If you install the role into your library folder it will load the plugin.
You can try with `ansible-galaxy install git+https://github.com/MartinNowak/ansible-ssh-config -p library/`.
I didn't try system wide installation, but it'll likely work as well.

**Comment by gaqzi** [comment]
@MartinNowak thank you! 
It's nice to finally have this available on Galaxy, last time I tried it didn't work at all :(

This has been merged in and tagged as [v0.3.0], new role name on galaxy is `gaqzi.ssh-config`.

[v0.3.0]: https://github.com/gaqzi/ansible-ssh-config/releases/tag/v0.3.0

**Comment by MartinNowak** [comment]
Great

**Comment by anatolykazantsev** [comment]
Installing the role into _library_ directory doesn't work in ansible 2.7. Also I don't see `path:` keyword (used _requirements.yaml_) in documentation.

So all mentioned ways to install it doesn't work in ansible 2.7

Also, [this comment](https://github.com/ansible/ansible/issues/16561#issuecomment-504170484) might explain why it doesn't work.

**Pull request closed without merging**
